os:
  - windows
language: node_js
node_js:
  - 12
cache:
  npm: false
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install graphicsmagick; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install imagemagick.app; fi
install: npm ci
jobs:
  include:
    - stage: "Testing on Windows"
      os: windows
      script: npm test