os:
  - osx
language: node_js
node_js:
  - 12
cache:
  npm: false
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install graphicsmagick; fi
install: npm ci
jobs:
  include:
    - stage: "Testing on OS X"
      os: osx
      script: npm test
addons:
  homebrew:
    update: false