os:
  - osx
  - linux
  - windows
language: node_js
node_js:
  - lts/*
  - 12
  - 10
cache:
  npm: false
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install graphicsmagick; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:rwky/graphicsmagick; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install graphicsmagick -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev libmagic-dev -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install imagemagick -y
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install graphicsmagick; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install imagemagick.app; fi
addons:
  apt:
    update: true
  homebrew:
    update: true
install: npm ci
jobs:
  include:
    - stage: "Unit Testing on Mac OS X"
      os: osx
      script: npm test
    - stage: "Unit Testing on Linux"
      os: linux
      script: npm test
    - stage: "Unit Testing on Windows"
      os: linux
      script: npm test