os:
  - linux
  - windows
language: node_js
node_js:
  - 12
cache:
  npm: false
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:rwky/graphicsmagick -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install graphicsmagick -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev libmagic-dev -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install imagemagick -y; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install graphicsmagick --version=1.3.31 --force -y; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install imagemagick.app --version=7.0.10.28 --force -y; fi
install: npm ci
jobs:
  include:
    - stage: "Testing on Linux"
      os: linux
      script: npm test

    - stage: "Testing on Windows"
      os: windows
      script: npm test